import { ATTR } from "../../../core/entity/attribute";
import type { MonsterDef, MonsterId } from "../../../core/content";
import type { AuthoringDef } from "../../compiler/inheritance";
import { CURRENCY_GOLD } from "../currencies";
import {
  beastHide,
  boneDust,
  bossCore,
  carapace,
  shadowCore,
  slimeGel,
  twilightEssence,
  wolfKingFang,
} from "../items";

// 早期怪物数值规则：
// - 同级怪物的成长强于玩家“裸升级”成长，因为玩家的大头强度来自装备与技能；
// - SPEED 只在少数教学怪上做明显偏移，其余大多保持在 40 左右；
// - 现阶段先只配数值，不给怪物配置主动技能机制。
export const earlyGameMonsterDrafts = {
  "monster.green_slime": {
    id: "monster.green_slime" as MonsterId,
    extends: "monster.template.base",
    name: "绿史莱姆",
    level: 1,
    baseAttrs: {
      [ATTR.MAX_HP]: 42,
      [ATTR.STR]: 6,
      [ATTR.WEAPON_ATK]: 4,
      [ATTR.PDEF]: 0,
      [ATTR.SPEED]: 40,
    },
    drops: [{ itemId: slimeGel.id, chance: 1, minQty: 1, maxQty: 1 }],
    xpReward: 3,
    currencyReward: { [CURRENCY_GOLD]: 1 },
  },
  "monster.slime": {
    id: "monster.slime" as MonsterId,
    extends: "monster.template.base",
    name: "史莱姆",
    level: 3,
    baseAttrs: {
      [ATTR.MAX_HP]: 72,
      [ATTR.STR]: 10,
      [ATTR.WEAPON_ATK]: 6,
      [ATTR.PDEF]: 1,
      [ATTR.SPEED]: 40,
    },
    xpReward: 10,
    currencyReward: { [CURRENCY_GOLD]: 2 },
  },
  "monster.wild_boar": {
    id: "monster.wild_boar" as MonsterId,
    extends: "monster.template.base",
    name: "野猪",
    level: 5,
    baseAttrs: {
      [ATTR.MAX_HP]: 112,
      [ATTR.STR]: 15,
      [ATTR.WEAPON_ATK]: 8,
      [ATTR.PDEF]: 2,
      [ATTR.SPEED]: 40,
    },
    xpReward: 18,
    currencyReward: { [CURRENCY_GOLD]: 3 },
  },
  "monster.horned_rabbit": {
    id: "monster.horned_rabbit" as MonsterId,
    extends: "monster.template.base",
    name: "角兔",
    level: 7,
    baseAttrs: {
      [ATTR.MAX_HP]: 96,
      [ATTR.STR]: 16,
      [ATTR.WEAPON_ATK]: 8,
      [ATTR.PDEF]: 1,
      [ATTR.SPEED]: 55,
    },
    drops: [{ itemId: beastHide.id, chance: 1, minQty: 1, maxQty: 1 }],
    xpReward: 25,
    currencyReward: { [CURRENCY_GOLD]: 3 },
  },
  "monster.big_slime": {
    id: "monster.big_slime" as MonsterId,
    extends: "monster.template.base",
    name: "大史莱姆",
    level: 8,
    baseAttrs: {
      [ATTR.MAX_HP]: 190,
      [ATTR.STR]: 20,
      [ATTR.WEAPON_ATK]: 9,
      [ATTR.PDEF]: 2,
      [ATTR.SPEED]: 35,
    },
    xpReward: 30,
    currencyReward: { [CURRENCY_GOLD]: 4 },
  },
  "monster.poison_mushroom": {
    id: "monster.poison_mushroom" as MonsterId,
    extends: "monster.template.base",
    name: "毒蘑菇",
    level: 9,
    baseAttrs: {
      [ATTR.MAX_HP]: 168,
      [ATTR.STR]: 18,
      [ATTR.WEAPON_ATK]: 8,
      [ATTR.PDEF]: 4,
      [ATTR.SPEED]: 40,
    },
    xpReward: 32,
    currencyReward: { [CURRENCY_GOLD]: 5 },
  },
  "monster.dusk_wolf": {
    id: "monster.dusk_wolf" as MonsterId,
    extends: "monster.template.base",
    name: "暮色狼",
    level: 12,
    baseAttrs: {
      [ATTR.MAX_HP]: 236,
      [ATTR.STR]: 24,
      [ATTR.WEAPON_ATK]: 11,
      [ATTR.PDEF]: 6,
      [ATTR.SPEED]: 40,
    },
    drops: [{ itemId: twilightEssence.id, chance: 1, minQty: 1, maxQty: 1 }],
    xpReward: 42,
    currencyReward: { [CURRENCY_GOLD]: 6 },
  },
  "monster.skeleton_soldier": {
    id: "monster.skeleton_soldier" as MonsterId,
    extends: "monster.template.base",
    name: "骸骨兵",
    level: 15,
    baseAttrs: {
      [ATTR.MAX_HP]: 310,
      [ATTR.STR]: 26,
      [ATTR.WEAPON_ATK]: 12,
      [ATTR.PDEF]: 52,
      [ATTR.MRES]: 0.05,
      [ATTR.SPEED]: 40,
    },
    xpReward: 55,
    currencyReward: { [CURRENCY_GOLD]: 7 },
  },
  "monster.dire_wolf": {
    id: "monster.dire_wolf" as MonsterId,
    extends: "monster.template.base",
    name: "巨狼",
    level: 16,
    baseAttrs: {
      [ATTR.MAX_HP]: 380,
      [ATTR.STR]: 32,
      [ATTR.WEAPON_ATK]: 14,
      [ATTR.PDEF]: 8,
      [ATTR.SPEED]: 45,
    },
    xpReward: 64,
    currencyReward: { [CURRENCY_GOLD]: 9 },
  },
  "monster.cave_bat": {
    id: "monster.cave_bat" as MonsterId,
    extends: "monster.template.base",
    name: "洞穴蝙蝠",
    level: 19,
    baseAttrs: {
      [ATTR.MAX_HP]: 220,
      [ATTR.STR]: 20,
      [ATTR.WEAPON_ATK]: 11,
      [ATTR.PDEF]: 6,
      [ATTR.SPEED]: 50,
    },
    xpReward: 68,
    currencyReward: { [CURRENCY_GOLD]: 8 },
  },
  "monster.shadow_fiend": {
    id: "monster.shadow_fiend" as MonsterId,
    extends: "monster.template.base",
    name: "暗影魔",
    level: 22,
    baseAttrs: {
      [ATTR.MAX_HP]: 392,
      [ATTR.STR]: 38,
      [ATTR.WEAPON_ATK]: 17,
      [ATTR.PDEF]: 10,
      [ATTR.MRES]: 0.55,
      [ATTR.SPEED]: 40,
    },
    xpReward: 78,
    currencyReward: { [CURRENCY_GOLD]: 11 },
  },
  "monster.ore_crab": {
    id: "monster.ore_crab" as MonsterId,
    extends: "monster.template.base",
    name: "矿石蟹",
    level: 24,
    baseAttrs: {
      [ATTR.MAX_HP]: 540,
      [ATTR.STR]: 30,
      [ATTR.WEAPON_ATK]: 14,
      [ATTR.PDEF]: 88,
      [ATTR.MRES]: 0.15,
      [ATTR.SPEED]: 35,
    },
    xpReward: 85,
    currencyReward: { [CURRENCY_GOLD]: 12 },
  },
  "monster.blackfang_alpha": {
    id: "monster.blackfang_alpha" as MonsterId,
    extends: "monster.template.base",
    name: "黑牙兽王",
    level: 27,
    baseAttrs: {
      [ATTR.MAX_HP]: 980,
      [ATTR.STR]: 48,
      [ATTR.WEAPON_ATK]: 20,
      [ATTR.PDEF]: 36,
      [ATTR.MRES]: 0.2,
      [ATTR.SPEED]: 45,
    },
    drops: [{ itemId: bossCore.id, chance: 1, minQty: 1, maxQty: 1 }],
    xpReward: 120,
    currencyReward: { [CURRENCY_GOLD]: 20 },
  },
  "monster.training_dummy": {
    id: "monster.training_dummy" as MonsterId,
    extends: "monster.template.base",
    name: "训练木人",
    baseAttrs: {
      [ATTR.MAX_HP]: 99999,
      [ATTR.STR]: 1,
      [ATTR.WEAPON_ATK]: 1,
      [ATTR.PDEF]: 0,
      [ATTR.SPEED]: 40,
    },
    xpReward: 1,
    currencyReward: { [CURRENCY_GOLD]: 0 },
  },
} satisfies Record<string, AuthoringDef<MonsterDef>>;
